# Generated by Django 3.0.5 on 2020-06-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallerry/')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutenactus',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='academicadvisors',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='academicadvisors',
            name='desc_en',
        ),
        migrations.RemoveField(
            model_name='academicadvisors',
            name='desc_ru',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='welcome',
            name='text',
        ),
        migrations.AddField(
            model_name='academicadvisors',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='academicadvisors',
            name='fb',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='academicadvisors',
            name='insta',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='academicadvisors',
            name='linkedin',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='nul', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='address_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='photo1',
            field=models.ImageField(default='non', upload_to='project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='project'),
        ),
        migrations.AddField(
            model_name='welcome',
            name='text_under_welcome',
            field=models.CharField(default='non', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='welcome',
            name='text_under_welcome_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='welcome',
            name='text_under_welcome_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='welcome',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='academicadvisors',
            name='photo',
            field=models.ImageField(upload_to='Our Team'),
        ),
        migrations.AlterField(
            model_name='academicadvisors',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='academicadvisors',
            name='position_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academicadvisors',
            name='position_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(upload_to='Partners'),
        ),
    ]
