# Generated by Django 3.0.5 on 2020-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_auto_20200601_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallerry',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_num2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_num3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
