# Generated by Django 3.0.5 on 2020-06-04 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0004_auto_20200601_1821'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallerry',
            new_name='Gallery',
        ),
    ]
