# Generated by Django 3.0.5 on 2020-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0005_auto_20200604_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='short_desc',
            field=models.CharField(default='this is the short desc', max_length=200),
            preserve_default=False,
        ),
    ]
