# Generated by Django 3.0.5 on 2020-07-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0006_projects_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='short_desc_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='short_desc_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
