# Generated by Django 3.0.5 on 2020-04-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutEnactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAdvisors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('f_name_ru', models.CharField(max_length=50, null=True)),
                ('f_name_en', models.CharField(max_length=50, null=True)),
                ('l_name', models.CharField(max_length=50)),
                ('l_name_ru', models.CharField(max_length=50, null=True)),
                ('l_name_en', models.CharField(max_length=50, null=True)),
                ('photo', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=100)),
                ('position_ru', models.CharField(max_length=100, null=True)),
                ('position_en', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=150)),
                ('desc_ru', models.CharField(max_length=150, null=True)),
                ('desc_en', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num1', models.CharField(max_length=30)),
                ('phone_num2', models.CharField(max_length=30)),
                ('phone_num3', models.CharField(max_length=30)),
                ('insta_link', models.CharField(max_length=150)),
                ('fb_link', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='')),
                ('web_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
    ]
