# Generated by Django 3.0.5 on 2020-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
