# Generated by Django 3.0.5 on 2020-04-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_aboutenactus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='web_link',
            field=models.CharField(max_length=100),
        ),
    ]
