# Generated by Django 3.0.5 on 2020-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0004_auto_20200413_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='name',
            field=models.CharField(default='partner 1', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutenactus',
            name='photo',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
